# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('RA', 'Rest API'), ('UI', 'User Interface')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('HYD', 'Hyderbad'), ('BANG', 'Bangalore'), ('che', 'Chennai')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
