# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-25 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquarydata',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
